#opensearch:
#  uris: https://search-movies-5jmf7lgf2emqczejio7xw4bgnu.aos.ap-northeast-2.on.aws
#  username: musinsa
#  password: Musinsa1!2@
opensearch:
  uris: http://localhost:9200

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true